import joeImg from "../Assets/paul-kapischka-M58gP7tAM54-unsplash.jpg"
import sarahImg from "../Assets/behrouz-sasani-5cDg40slYoc-unsplash.jpg"
import burkeImg from "../Assets/marie-michele-bouchard-bEZQWH49daU-unsplash.jpg"
import kellyImg from "../Assets/troy-wade-dYgyzxlHJ58-unsplash.jpg"
import baileyImg from "../Assets/jimmy-fermin-bqe0J0b26RQ-unsplash.jpg"

export const MailData = [
    {
        id: 1,
        starred: true,
        subject: "Failed purchase when trying to get a Gucci bag.",
        brief: "For some time now, I have been trying to purchases a Gucci bag form Simply's online rvvjnt",
        mailImg: kellyImg,
        timeline: "2 hours ago",
        label: ["Clients", "Issues"],
    },
    {
        id: 2,
        starred: false,
        subject: "Failed purchase when trying to get a Gucci bag.",
        brief: "For some time now, I have been trying to purchases a Gucci bag form Simply's online rvvjnt",
        mailImg: kellyImg,
        timeline: "2 hours ago",
        label: ["Clients", "Issues", "Social"],
    },
    {
        id: 3,
        starred: false,
        subject: "Failed purchase when trying to get a Gucci bag.",
        brief: "For some time now, I have been trying to purchases a Gucci bag form Simply's online rvvjnt",
        mailImg: kellyImg,
        timeline: "2 hours ago",
        label: ["Social", "Issues"],
    },
    {
        id: 4,
        starred: true,
        subject: "Failed purchase when trying to get a Gucci bag.",
        brief: "For some time now, I have been trying to purchases a Gucci bag form Simply's online rvvjnt",
        mailImg: kellyImg,
        timeline: "2 hours ago",
        label: ["Clients"],
    },
    {
        id: 5,
        starred: true,
        subject: "Failed purchase when trying to get a Gucci bag.",
        brief: "For some time now, I have been trying to purchases a Gucci bag form Simply's online rvvjnt",
        mailImg: kellyImg,
        timeline: "2 hours ago",
        label: ["Clients", "Issues"],
    },
    {
        id: 6,
        starred: true,
        subject: "Failed purchase when trying to get a Gucci bag.",
        brief: "For some time now, I have been trying to purchases a Gucci bag form Simply's online rvvjnt",
        mailImg: kellyImg,
        timeline: "2 hours ago",
        label: ["Clients", "Issues"],
    },
    {
        id: 7,
        starred: true,
        subject: "Failed purchase when trying to get a Gucci bag.",
        brief: "For some time now, I have been trying to purchases a Gucci bag form Simply's online rvvjnt",
        mailImg: kellyImg,
        timeline: "2 hours ago",
        label: ["Clients", "Issues"],
    },
    {
        id: 8,
        starred: true,
        subject: "Failed purchase when trying to get a Gucci bag.",
        brief: "For some time now, I have been trying to purchases a Gucci bag form Simply's online rvvjnt",
        mailImg: kellyImg,
        timeline: "2 hours ago",
        label: ["Clients", "Issues"],
    },
    {
        id: 9,
        starred: true,
        subject: "Failed purchase when trying to get a Gucci bag.",
        brief: "For some time now, I have been trying to purchases a Gucci bag form Simply's online rvvjnt",
        mailImg: kellyImg,
        timeline: "2 hours ago",
        label: ["Clients", "Issues"],
    },
    {
        id: 10,
        starred: true,
        subject: "Failed purchase when trying to get a Gucci bag.",
        brief: "For some time now, I have been trying to purchases a Gucci bag form Simply's online rvvjnt",
        mailImg: kellyImg,
        timeline: "2 hours ago",
        label: ["Clients", "Issues"],
    },
    {
        id: 11,
        starred: true,
        subject: "Failed purchase when trying to get a Gucci bag.",
        brief: "For some time now, I have been trying to purchases a Gucci bag form Simply's online rvvjnt",
        mailImg: kellyImg,
        timeline: "2 hours ago",
        label: ["Clients", "Issues"],
    },
    {
        id: 12,
        starred: true,
        subject: "Failed purchase when trying to get a Gucci bag.",
        brief: "For some time now, I have been trying to purchases a Gucci bag form Simply's online rvvjnt",
        mailImg: kellyImg,
        timeline: "2 hours ago",
        label: ["Clients", "Issues"],
    },
    {
        id: 13,
        starred: true,
        subject: "Failed purchase when trying to get a Gucci bag.",
        brief: "For some time now, I have been trying to purchases a Gucci bag form Simply's online rvvjnt",
        mailImg: kellyImg,
        timeline: "2 hours ago",
        label: ["Clients", "Issues"],
    },
    {
        id: 14,
        starred: true,
        subject: "Failed purchase when trying to get a Gucci bag.",
        brief: "For some time now, I have been trying to purchases a Gucci bag form Simply's online rvvjnt",
        mailImg: kellyImg,
        timeline: "2 hours ago",
        label: ["Clients", "Issues"],
    },
    {
        id: 15,
        starred: true,
        subject: "Failed purchase when trying to get a Gucci bag.",
        brief: "For some time now, I have been trying to purchases a Gucci bag form Simply's online rvvjnt",
        mailImg: kellyImg,
        timeline: "2 hours ago",
        label: ["Clients", "Issues"],
    },
    {
        id: 16,
        starred: true,
        subject: "Failed purchase when trying to get a Gucci bag.",
        brief: "For some time now, I have been trying to purchases a Gucci bag form Simply's online rvvjnt",
        mailImg: kellyImg,
        timeline: "2 hours ago",
        label: ["Clients", "Issues"],
    },
    {
        id: 17,
        starred: true,
        subject: "Failed purchase when trying to get a Gucci bag.",
        brief: "For some time now, I have been trying to purchases a Gucci bag form Simply's online rvvjnt",
        mailImg: kellyImg,
        timeline: "2 hours ago",
        label: ["Clients", "Issues"],
    },
    {
        id: 18,
        starred: true,
        subject: "Failed purchase when trying to get a Gucci bag.",
        brief: "For some time now, I have been trying to purchases a Gucci bag form Simply's online rvvjnt",
        mailImg: kellyImg,
        timeline: "2 hours ago",
        label: ["Clients", "Issues"],
    },
]